name: 'ecobici_dbt'
version: '1.0.0'
config-version: 2

profile: 'ecobici_profile'

model-paths: ["models"]

models:
  ecobici_dbt:
    staging:
      materialized: view
    core:
      materialized: table
